apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-devops-deployment
  labels:
    app: hello-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-devops
  template:
    metadata:
      labels:
        app: hello-devops
    spec:
      containers:
      - name: hello-devops
        image: icyberx/hello_devops:1.0.0.4
        ports:
        - containerPort: 80