apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello_devops-deployment
  labels:
    app: hello_devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello_devops
  template:
    metadata:
      labels:
        app: hello_devops
    spec:
      containers:
      - name: hello_devops
        image: icyberx/hello_devops:1.0.0.2
        ports:
        - containerPort: 80